development:
  host: dc-noc.puhsd.org
  port: 636
  encryption: :simple_tls
  attribute: sAMAccountName
  base: ou=staff,ou=accounts,dc=puhsd,dc=org
  admin_username: adauthenticate@puhsd.org
  admin_password: "L1ghts@b3r"
  ssl: false
  read-attributes: [
                "dn",
                "samaccountname",
                "mail",
                "displayname",
                "employeenumber",
                "memberof",
                "sn",
                "givenname",
                "physicaldeliveryofficename",
                "useraccountcontrol",
                "employeetype",
                "ipphone",
                "title",
                "company",
                "description",
                "objectguid",
                "samaccounttype",
                "accountexpires",
                "whenchanged",
                "whencreated"
              ]

test:
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: false
  # <<: *AUTHORIZATIONS

production:
  host: 10.80.20.110
  port: 636
  encryption: :simple_tls
  attribute: sAMAccountName
  base: ou=staff,ou=accounts,dc=puhsd,dc=org
  admin_username: adauthenticate@puhsd.org
  admin_password: "L1ghts@b3r"
  ssl: false
  read-attributes: [
                "dn",
                "samaccountname",
                "mail",
                "displayname",
                "employeenumber",
                "memberof",
                "sn",
                "givenname",
                "physicaldeliveryofficename",
                "useraccountcontrol",
                "employeetype",
                "ipphone",
                "title",
                "company",
                "description",
                "objectguid",
                "samaccounttype",
                "accountexpires",
                "whenchanged",
                "whencreated"
              ]

  # <<: *AUTHORIZATIONS
